version: "3.3"

volumes:
  sqlite_volume:

services:
  parser:
    build: Parser
    restart: always
    volumes:
      - sqlite_volume:/usr/src/db/
  app:
    build: App
    restart: always
    volumes:
      - sqlite_volume:/usr/src/db/
    ports:
      - 5000:5000
